# Generated by Django 5.0 on 2023-12-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_packet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
